language: objective-c
xcode_workspace: Example/Example.xcworkspace
xcode_scheme: Example
podfile: Example/Podfile

script:
  xctool
  -workspace Example/Example.xcworkspace
  -scheme Example
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build 
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
