language: objective-c
xcode_workspace: Example/Example.xcworkspace
xcode_scheme: Example
podfile: Example/Podfile

script:
  xctool -workspace Example.xcworkspace -scheme Example clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
